language: php
php:
  -"5.6"
  -"7.2"
before_install:
  - php /home/travis/.phpenv/versions/5.6/bin/composer self-update
before_script:
  -composer install
script: phpunit --configuration phpunit.xml --coverage-text